---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: spring-rest-services
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: spring-rest-services@sha256:f0543571c9a72494f2869118b45ce743ea44dd2a67d0175c18ac482a094051e4
        namespace: dev
      name: latest
